config/routes.rb
Rails.application.routes.draw do

  
  devise_for :users
  resources :categories
  resources :newborns
  root 'home#index'

end

app/models/category.rb
class Category < ActiveRecord::Base
	
end

app/models/newborn.rb
class Newborn < ActiveRecord::Base	
	belongs_to :user
	validates :first_name, presence: true
	validates :last_name, presence: true
	validates :gender, presence: true
	validates :birthdate, presence: true
	validates :photo, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

 has_many :newborns
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

	def index
		@categories = Category.all
	end

	def show
		@category = Category.find(params[:id])
		@users = @Category.users
	end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	
	def index

	end
end

app/controllers/newborns_controller.rb
class NewbornsController < ApplicationController

	def index
		@newborns = Newborn.all
	end

	def show
		@newborn = Newborn.find(params[:id])		
	end

	def new
		@newborn = Newborn.new
	end

	def create
		@newborn = Newborn.new(newborn_params)
		if @newborn.save
		redirect_to @newborn
		else
		render :new
		end
	end

	def destroy
		@newborn = Newborn.find(params[:id])
		@newborn.destroy
		redirect_to newborns_path
	end
	def edit
		@newborn = Newborn.find(params[:id])		
	end
	def update
		@newborn = Newborn.find(params[:id])
		if @newborn.update(newborn_params)
			redirect_to @newborn
		else
			render :edit
		end
		
		
	end

	private

	def newborn_params
		params.require(:newborn).permit(:first_name,:last_name,:birthdate,:gender,:photo)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/newborns_helper.rb
module NewbornsHelper
end

app/views/categories/index.html.erb
<div class="row">
  
 
  <% @categories.each do |a|%>
  <div class="col-md-3">
    <%= link_to (a) do %>
      <div class="thumbnail">
        <img src="http://codeproject.cachefly.net/App_Themes/CodeProject/Img/logo250x135.gif">
        <div class="caption">
          <h3 class="title"><%= a.name%>  </h3>          
        </div>
      </div>
    <% end %>
     <% end %>
  </div>
  
  
</div>

app/views/categories/show.html.erb
<div class="show row">
  <div class="cover col-md-4">  </div>  
  <div class="col-sm-8">
    <h3 class="album-title"><%=  @categories.name%> </h3>

   
    
    <% @users.each do |t|%>
    <div class="track row">
      <div class="name col-md-8"> <%= t.first_name%> </div>
    </div>
    <%end %>
    
  </div>
</div>

app/views/home/index.html.erb

		<div class="homepage_left">
			
				<div class="row" style="margin-top: 0;">
					<div class="bebes">
						bebes
					</div>
				</div>
					
				
				<div class="row">
					<div class="modulo1">
						Lorem ipsum dolor sit amet, consectetur adipisicing elit. Hic laboriosam, dolorem aliquam quas velit doloremque, facere maxime architecto tempore dolor ad obcaecati officia necessitatibus esse ea, quaerat? Neque mollitia, perferendis.
					</div>
					<div class="modulo2">
						Lorem ipsum dolor sit amet, consectetur adipisicing elit. Suscipit animi recusandae aliquam enim facere accusantium amet nam! Hic accusantium, tenetur! Tempora repellendus amet, laboriosam nobis, rem error consequuntur sunt adipisci.
					</div>
				</div>

				<div class="row">
					<div class="modulo3">
						Lorem ipsum dolor sit amet, consectetur adipisicing elit. Hic laboriosam, dolorem aliquam quas velit doloremque, facere maxime architecto tempore dolor ad obcaecati officia necessitatibus esse ea, quaerat? Neque mollitia, perferendis.
					</div>
					<div class="modulo4">
						Lorem ipsum dolor sit amet, consectetur adipisicing elit. Suscipit animi recusandae aliquam enim facere accusantium amet nam! Hic accusantium, tenetur! Tempora repellendus amet, laboriosam nobis, rem error consequuntur sunt adipisci.
					</div>
				</div>
				
			
		</div>


		<div class="homepage_right">

				<div class="doc">
					<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sequi ipsa distinctio voluptatem illum animi, totam alias quisquam ducimus, velit laborum, in sed eos delectus maxime ea consectetur expedita nesciunt dolor.</p>
				</div>

				<div class="isq">
					<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sequi ipsa distinctio voluptatem illum animi, totam alias quisquam ducimus, velit laborum, in sed eos delectus maxime ea consectetur expedita nesciunt dolor.</p>
				</div>

				<div class="isq">
					<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sequi ipsa distinctio voluptatem illum animi, totam alias quisquam ducimus, velit laborum, in sed eos delectus maxime ea consectetur expedita nesciunt dolor.</p>
				</div>
			
			</div>
		</div>
	

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ccsc</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<header>
<p class="notice"><%= notice %></p>
        <p class="alert"><%= alert %></p>

		<%= render "partials/navigation"%>
	</header>
	<div class="container">
		<%= yield %>
	</div>

<footer>
	<div class="container">
		<div class="row">
			este es el footer
		</div>
	</div>
</footer>

</body>
</html>

app/views/newborns/_form.html.erb
<div class="new-newborn">
	<%= form_for(@newborn) do |n|%>
<% @newborn.errors.full_messages.each do |m|%>
	<div><%= m %></div>
	
<%end%>


	<div class="form-group">
			<div class="input-group">
		  		<span class="input-group-addon" id="basic-addon1">Nombre</span>
		  		<%= n.text_field :first_name , placeholder: "" , class:"form-control"%>
			</div>
		</div>	

		<div class="form-group">
			<div class="input-group">
		  		<span class="input-group-addon" id="basic-addon1">Apellido</span>
		  		<%= n.text_field :last_name , placeholder: "" , class:"form-control"%>
			</div>
		</div>

	<div class="form-group">
			<div class="input-group">
		  		<span class="input-group-addon" id="basic-addon1">Genero</span>
		  		<%= n.text_field :gender , class:"form-control"%>
			</div>
		</div>
			
	  	
	  	<div class="form-group">
            <div class="input-group date">
            <span class="input-group-addon" id="basic-addon1">Nacimiento</span>
 			 <%= n.text_field :birthdate  , class:"form-control white"%><span class="input-group-addon"><i class="glyphicon glyphicon-th"></i></span>
			</div>
    	 </div>

    	 <div class="form-group">
			<div class="input-group">
		  		<span class="input-group-addon" id="basic-addon1">Foto</span>
		  		<%= n.text_field :photo , class:"form-control"%>
			</div>
		</div>
		<p>NOTA: Ya se que faltan datos :(</p>
</div>

<div class="new-newborn" style="margin-bottom: 10%;">
<div class="image-upload">modulo para subir imagen</div>
	<%= n.submit "Guardar", class:"btn" %>
</div>
<%end%>

app/views/newborns/edit.html.erb
<h1 style="text-align: center;">Editar Bebe</h1>
<%= render "form"%>

           

app/views/newborns/index.html.erb

<div class="busqueda">		  		
	<input type="text" placeholder="Nombre o Apellido" class="form-control">	
</div>

	

	<% @newborns.each do |newborn| %>	
		<%= link_to(newborn) do %>
		<div class="item">
			
			<div class="cont">
				<img class="imagen" src="/baby-cut.jpg" alt="un bebe adorable">
			<h3><%= newborn.first_name %></h3>
			<h3 style="margin-top: 0;"><%= newborn.last_name %></h3>			
			<p><%= newborn.birthdate %></p>
			<% if user_signed_in? %>
			<%= link_to "Eliminar", newborn, method: :delete%> <%= link_to "Editar", edit_newborn_path(newborn)%>
			<%end%>
			</div>
		</div>	
		<%end%>
	<%end%>
	


	
	




	

app/views/newborns/new.html.erb
<h1 style="text-align: center;">Registrar Bebe</h1>
<%= render "form"%>

app/views/newborns/show.html.erb



<div class="baby-big">
	

<img  class="image-baby-big" src="/baby.jpg">
<h1><%= @newborn.first_name %></h1>
<h1><%= @newborn.last_name %></h1><br><br><br>
<h3><%= @newborn.birthdate %></h3>
	
</div>

app/views/partials/_navigation.html.erb
<div class="container">
		<div class="row">
			<ul class="nav">
				  <li role="presentation"><%= link_to "Home", root_path %></li>
				  <li role="presentation"><%= link_to "Recien Nacidos", newborns_path %></li>

				  <% if user_signed_in? %>
				  	<li role="presentation"><a href="/newborns/new">Registrar Recien Nacido</a></li>
				  	<li role="presentation"><%= link_to "Cerrar Sesion", destroy_user_session_path, method: :delete %></li>
				  <% else%>
				  	<li role="presentation"><%= link_to "Iniciar Sesion", new_user_session_path %></li>
				  <% end %>
			</ul>
		</div>
				
		</div>